// Generated by gencpp from file panda_ik/pandaIkRequest.msg
// DO NOT EDIT!


#ifndef PANDA_IK_MESSAGE_PANDAIKREQUEST_H
#define PANDA_IK_MESSAGE_PANDAIKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <sensor_msgs/JointState.h>

namespace panda_ik
{
template <class ContainerAllocator>
struct pandaIkRequest_
{
  typedef pandaIkRequest_<ContainerAllocator> Type;

  pandaIkRequest_()
    : reference_pose()
    , seed_joints()  {
    }
  pandaIkRequest_(const ContainerAllocator& _alloc)
    : reference_pose(_alloc)
    , seed_joints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _reference_pose_type;
  _reference_pose_type reference_pose;

   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _seed_joints_type;
  _seed_joints_type seed_joints;





  typedef boost::shared_ptr< ::panda_ik::pandaIkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_ik::pandaIkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pandaIkRequest_

typedef ::panda_ik::pandaIkRequest_<std::allocator<void> > pandaIkRequest;

typedef boost::shared_ptr< ::panda_ik::pandaIkRequest > pandaIkRequestPtr;
typedef boost::shared_ptr< ::panda_ik::pandaIkRequest const> pandaIkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_ik::pandaIkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_ik::pandaIkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_ik::pandaIkRequest_<ContainerAllocator1> & lhs, const ::panda_ik::pandaIkRequest_<ContainerAllocator2> & rhs)
{
  return lhs.reference_pose == rhs.reference_pose &&
    lhs.seed_joints == rhs.seed_joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_ik::pandaIkRequest_<ContainerAllocator1> & lhs, const ::panda_ik::pandaIkRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaIkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaIkRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaIkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2acb58c4e6d61c85039d7bc6cff7d6d";
  }

  static const char* value(const ::panda_ik::pandaIkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2acb58c4e6d61c8ULL;
  static const uint64_t static_value2 = 0x5039d7bc6cff7d6dULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_ik/pandaIkRequest";
  }

  static const char* value(const ::panda_ik::pandaIkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose reference_pose\n"
"sensor_msgs/JointState seed_joints\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::panda_ik::pandaIkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reference_pose);
      stream.next(m.seed_joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pandaIkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_ik::pandaIkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_ik::pandaIkRequest_<ContainerAllocator>& v)
  {
    s << indent << "reference_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.reference_pose);
    s << indent << "seed_joints: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.seed_joints);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_IK_MESSAGE_PANDAIKREQUEST_H
