// Generated by gencpp from file panda_ik/pandaIkResponse.msg
// DO NOT EDIT!


#ifndef PANDA_IK_MESSAGE_PANDAIKRESPONSE_H
#define PANDA_IK_MESSAGE_PANDAIKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/JointState.h>

namespace panda_ik
{
template <class ContainerAllocator>
struct pandaIkResponse_
{
  typedef pandaIkResponse_<ContainerAllocator> Type;

  pandaIkResponse_()
    : solution()
    , success(false)  {
    }
  pandaIkResponse_(const ContainerAllocator& _alloc)
    : solution(_alloc)
    , success(false)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::JointState_<ContainerAllocator>  _solution_type;
  _solution_type solution;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::panda_ik::pandaIkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_ik::pandaIkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pandaIkResponse_

typedef ::panda_ik::pandaIkResponse_<std::allocator<void> > pandaIkResponse;

typedef boost::shared_ptr< ::panda_ik::pandaIkResponse > pandaIkResponsePtr;
typedef boost::shared_ptr< ::panda_ik::pandaIkResponse const> pandaIkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_ik::pandaIkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_ik::pandaIkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_ik::pandaIkResponse_<ContainerAllocator1> & lhs, const ::panda_ik::pandaIkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.solution == rhs.solution &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_ik::pandaIkResponse_<ContainerAllocator1> & lhs, const ::panda_ik::pandaIkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaIkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaIkResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaIkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d492d07fea71104fe59769bb19fedae3";
  }

  static const char* value(const ::panda_ik::pandaIkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd492d07fea71104fULL;
  static const uint64_t static_value2 = 0xe59769bb19fedae3ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_ik/pandaIkResponse";
  }

  static const char* value(const ::panda_ik::pandaIkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/JointState solution\n"
"bool success\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::panda_ik::pandaIkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solution);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pandaIkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_ik::pandaIkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_ik::pandaIkResponse_<ContainerAllocator>& v)
  {
    s << indent << "solution: ";
    s << std::endl;
    Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.solution);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_IK_MESSAGE_PANDAIKRESPONSE_H
