// Generated by gencpp from file panda_ik/pandaFk.msg
// DO NOT EDIT!


#ifndef PANDA_IK_MESSAGE_PANDAFK_H
#define PANDA_IK_MESSAGE_PANDAFK_H

#include <ros/service_traits.h>


#include <panda_ik/pandaFkRequest.h>
#include <panda_ik/pandaFkResponse.h>


namespace panda_ik
{

struct pandaFk
{

typedef pandaFkRequest Request;
typedef pandaFkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pandaFk
} // namespace panda_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_ik::pandaFk > {
  static const char* value()
  {
    return "cf41e0feb1f85dd54246ca565d37eb4f";
  }

  static const char* value(const ::panda_ik::pandaFk&) { return value(); }
};

template<>
struct DataType< ::panda_ik::pandaFk > {
  static const char* value()
  {
    return "panda_ik/pandaFk";
  }

  static const char* value(const ::panda_ik::pandaFk&) { return value(); }
};


// service_traits::MD5Sum< ::panda_ik::pandaFkRequest> should match
// service_traits::MD5Sum< ::panda_ik::pandaFk >
template<>
struct MD5Sum< ::panda_ik::pandaFkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_ik::pandaFk >::value();
  }
  static const char* value(const ::panda_ik::pandaFkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_ik::pandaFkRequest> should match
// service_traits::DataType< ::panda_ik::pandaFk >
template<>
struct DataType< ::panda_ik::pandaFkRequest>
{
  static const char* value()
  {
    return DataType< ::panda_ik::pandaFk >::value();
  }
  static const char* value(const ::panda_ik::pandaFkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_ik::pandaFkResponse> should match
// service_traits::MD5Sum< ::panda_ik::pandaFk >
template<>
struct MD5Sum< ::panda_ik::pandaFkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_ik::pandaFk >::value();
  }
  static const char* value(const ::panda_ik::pandaFkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_ik::pandaFkResponse> should match
// service_traits::DataType< ::panda_ik::pandaFk >
template<>
struct DataType< ::panda_ik::pandaFkResponse>
{
  static const char* value()
  {
    return DataType< ::panda_ik::pandaFk >::value();
  }
  static const char* value(const ::panda_ik::pandaFkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_IK_MESSAGE_PANDAFK_H
