// Generated by gencpp from file panda_ik/pandaFkResponse.msg
// DO NOT EDIT!


#ifndef PANDA_IK_MESSAGE_PANDAFKRESPONSE_H
#define PANDA_IK_MESSAGE_PANDAFKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace panda_ik
{
template <class ContainerAllocator>
struct pandaFkResponse_
{
  typedef pandaFkResponse_<ContainerAllocator> Type;

  pandaFkResponse_()
    : solution()  {
    }
  pandaFkResponse_(const ContainerAllocator& _alloc)
    : solution(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _solution_type;
  _solution_type solution;





  typedef boost::shared_ptr< ::panda_ik::pandaFkResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_ik::pandaFkResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pandaFkResponse_

typedef ::panda_ik::pandaFkResponse_<std::allocator<void> > pandaFkResponse;

typedef boost::shared_ptr< ::panda_ik::pandaFkResponse > pandaFkResponsePtr;
typedef boost::shared_ptr< ::panda_ik::pandaFkResponse const> pandaFkResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_ik::pandaFkResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_ik::pandaFkResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_ik::pandaFkResponse_<ContainerAllocator1> & lhs, const ::panda_ik::pandaFkResponse_<ContainerAllocator2> & rhs)
{
  return lhs.solution == rhs.solution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_ik::pandaFkResponse_<ContainerAllocator1> & lhs, const ::panda_ik::pandaFkResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_ik::pandaFkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_ik::pandaFkResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_ik::pandaFkResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3595aa8695ee087c6cee665c0f6958e2";
  }

  static const char* value(const ::panda_ik::pandaFkResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3595aa8695ee087cULL;
  static const uint64_t static_value2 = 0x6cee665c0f6958e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_ik/pandaFkResponse";
  }

  static const char* value(const ::panda_ik::pandaFkResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose solution\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::panda_ik::pandaFkResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pandaFkResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_ik::pandaFkResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_ik::pandaFkResponse_<ContainerAllocator>& v)
  {
    s << indent << "solution: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.solution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_IK_MESSAGE_PANDAFKRESPONSE_H
