// Generated by gencpp from file panda_ik/pandaIk.msg
// DO NOT EDIT!


#ifndef PANDA_IK_MESSAGE_PANDAIK_H
#define PANDA_IK_MESSAGE_PANDAIK_H

#include <ros/service_traits.h>


#include <panda_ik/pandaIkRequest.h>
#include <panda_ik/pandaIkResponse.h>


namespace panda_ik
{

struct pandaIk
{

typedef pandaIkRequest Request;
typedef pandaIkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pandaIk
} // namespace panda_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::panda_ik::pandaIk > {
  static const char* value()
  {
    return "65f8d44d8abe540af29b0f9c556cdb12";
  }

  static const char* value(const ::panda_ik::pandaIk&) { return value(); }
};

template<>
struct DataType< ::panda_ik::pandaIk > {
  static const char* value()
  {
    return "panda_ik/pandaIk";
  }

  static const char* value(const ::panda_ik::pandaIk&) { return value(); }
};


// service_traits::MD5Sum< ::panda_ik::pandaIkRequest> should match
// service_traits::MD5Sum< ::panda_ik::pandaIk >
template<>
struct MD5Sum< ::panda_ik::pandaIkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::panda_ik::pandaIk >::value();
  }
  static const char* value(const ::panda_ik::pandaIkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_ik::pandaIkRequest> should match
// service_traits::DataType< ::panda_ik::pandaIk >
template<>
struct DataType< ::panda_ik::pandaIkRequest>
{
  static const char* value()
  {
    return DataType< ::panda_ik::pandaIk >::value();
  }
  static const char* value(const ::panda_ik::pandaIkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::panda_ik::pandaIkResponse> should match
// service_traits::MD5Sum< ::panda_ik::pandaIk >
template<>
struct MD5Sum< ::panda_ik::pandaIkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::panda_ik::pandaIk >::value();
  }
  static const char* value(const ::panda_ik::pandaIkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::panda_ik::pandaIkResponse> should match
// service_traits::DataType< ::panda_ik::pandaIk >
template<>
struct DataType< ::panda_ik::pandaIkResponse>
{
  static const char* value()
  {
    return DataType< ::panda_ik::pandaIk >::value();
  }
  static const char* value(const ::panda_ik::pandaIkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PANDA_IK_MESSAGE_PANDAIK_H
